// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HelloService.proto
// Protobuf Java Version: 4.29.3

package com.grpcstudy.grpcstudy.services;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      HelloServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcstudy_grpcstudy_Services_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_grpcstudy_grpcstudy_Services_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcstudy_grpcstudy_Services_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_grpcstudy_grpcstudy_Services_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HelloService.proto\022 com.grpcstudy.grpc" +
      "study.Services\"3\n\014HelloRequest\022\021\n\tfirstN" +
      "ame\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\"!\n\rHelloResp" +
      "onse\022\020\n\010greeting\030\001 \001(\t2x\n\014HelloService\022h" +
      "\n\005hello\022..com.grpcstudy.grpcstudy.Servic" +
      "es.HelloRequest\032/.com.grpcstudy.grpcstud" +
      "y.Services.HelloResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_grpcstudy_grpcstudy_Services_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpcstudy_grpcstudy_Services_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_grpcstudy_grpcstudy_Services_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_com_grpcstudy_grpcstudy_Services_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpcstudy_grpcstudy_Services_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_grpcstudy_grpcstudy_Services_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
