// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HelloService.proto
// Protobuf Java Version: 4.29.3

package com.grpcstudy.grpcstudy.services;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpcstudy.grpcstudy.Services.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
